### PR TITLE
feat: enable filters for custom dimensions

### PR DESCRIPTION
**Pull request by margau**
This MR is a first implementation step for https://github.com/akvorado/akvorado/issues/852

With this MR, there can now be filters for runtime-defined dynamic Dimensions (e.g. from custom dicts). 
This works by adding a "catch all dimensions" Expression to the filtering grammar, which explicitly excludes well-known dimension names (thats why there is a large diff in parser.peg, separating column name literals from expressions). 

For now, it is assumed that all custom dimensions are of type string or compatible.

Completion does not yet work for the custom dictionaries, the full dimensions needs to be entered manually.

According to the unit tests and my manual tests, the functionality for other dimensions should have been kept.

### CODE REVIEW

**Comment by margau** [comment]
I've also added the completion part as separate commit (if feasible, I could also split this up into separate PRs).
autocompletion is done by directly looking into the schema, as the grammar is not able to provide the column names as literals.

**Comment by vincentbernat** [comment]
I was thinking it would be possible to be smarter in `filter.peg`. The directions I provided to you were not totally correct but I just pushed a commit showing how to do that. I have reused some of your tests to check if everything was working as expected.

What's missing:
- IPv4 handling
- value completion (you already have the code, I didn't want to "steal" more than what's necessary)

Maybe it would be easier to have another PR for that?

**Comment by vincentbernat** [comment]
Done in 6e18065be663.

**Comment by vincentbernat** [comment]
Note that I did remove the ability to use IPv4 as a type. People should use IPv6 (even if they only have IPv4) as all the code is handling IPv6, not IPv4. It wasn't even possible to display IPv4, I think.

**Pull request closed without merging**
